### ISSUE TITLE
What does this bit of code do?

### ISSUE THREAD

**Issue by cameronbratcher** [josepharhar/dotfiles#2]
In install.sh what does this do? It's right after when you install zsh.

mkpasswd -c | sed -e 'sX/bashX/zshX' | tee -a /etc/passwd

I'm trying to make this script more linux friendly and mkpasswd isn't on linux so I'm not sure exactly what it does.

**Comment by cameronbratcher** [comment]
I think I figured it out, this is to change the users shell right? I'll have to do this differently on linux as opposed to cygwin. Correct me if I'm wrong.

**Comment by josepharhar** [comment]
Yeah, it's to change the default shell on Cygwin. I found it on stackoverflow

**Comment by cameronbratcher** [comment]
Fixed in 25f447e
